### ISSUE TITLE
 Issue with Importing positional_marked_npairs_3d from halotools.mock_observables.pair_counters

### ISSUE THREAD

**Issue by mi-song** [astropy/halotools#1074]
I've encountered an issue when trying to run my code which utilizes the halotools library. Specifically, I'm having trouble importing the positional_marked_npairs_3d function from the halotools.mock_observables.pair_counters module.

Here's the error traceback I received:

Traceback (most recent call last):
  File "C:\Users\82103\Desktop\graphgan\GraphGAN\2d_alignment.py", line 12, in <module>
    from halotools_ia.correlation_functions import ed_3d, ee_3d, ed_3d_one_two_halo_decomp
  File "C:\Users\82103\Desktop\graphgan\GraphGAN\halotools_ia\correlation_functions\__init__.py", line 11, in <module>
    from .ed_3d import ed_3d
  File "C:\Users\82103\Desktop\graphgan\GraphGAN\halotools_ia\correlation_functions\ed_3d.py", line 15, in <module>
    from halotools.mock_observables.pair_counters import positional_marked_npairs_3d, npairs_3d, marked_npairs_3d
ImportError: cannot import name 'positional_marked_npairs_3d' from 'halotools.mock_observables.pair_counters' (C:\Users\82103\.conda\envs\galaxygan\lib\site-packages\halotools\mock_observables\pair_counters\__init__.py)

I've tried using both version 0.8.0 and 0.8.2 of halotools, but encountered the same error in both versions. I've verified my halotools installation and even tried different versions, but the issue persists. I'm wondering if this function has been moved to a different module or if there might be some other underlying issue I'm not aware of.

Any guidance or assistance on this matter would be greatly appreciated.

Thank you for your time and consideration.

**Comment by nvanalfen** [comment]
@mi-song I think I see what happened, please let me know if this helps.

We indeed did move some things around. Specifically, halotools_ia (from your import) no longer exists and had been merged into halotools itself.

The import for what you want should now be
from halotools.mock_observables.ia_correlations import ed_3d, ee_3d, ed_3d_one_two_halo_decomp

Please try this out and let me know if it fixes things. If not, ping me on your next reply and I'll keep looking into it

**Comment by aphearin** [comment]
@mi-song did this resolve your issue?
