### ISSUE TITLE
Bug in PrebuiltSubhaloModelFactory redshift behavior

### ISSUE THREAD

**Issue by aphearin** [astropy/halotools#304]
In [1]: from halotools.empirical_models import PrebuiltSubhaloModelFactory

In [2]: behroozi_model = PrebuiltSubhaloModelFactory('behroozi10', redshift = 2)

In [3]: behroozi_model.populate_mock(simname = 'bolplanck', redshift = 2)

In [4]: r, xi = behroozi_model.compute_average_galaxy_matter_cross_clustering(simname = 'bolplanck', redshift=2)

Traceback (most recent call last):
  File "<ipython-input-9-0fe0c417a378>", line 2, in <module>
    r, xi = behroozi_model.compute_average_galaxy_matter_cross_clustering(simname = 'bolplanck', redshift=2)
  File "/Users/aphearin/anaconda/lib/python2.7/site-packages/halotools-0.0a0-py2.7-macosx-10.5-x86_64.egg/halotools/empirical_models/factories/model_factory_template.py", line 543, in compute_average_galaxy_matter_cross_clustering
    self.populate_mock(halocat = halocat)
  File "/Users/aphearin/anaconda/lib/python2.7/site-packages/halotools-0.0a0-py2.7-macosx-10.5-x86_64.egg/halotools/empirical_models/factories/subhalo_model_factory.py", line 875, in populate_mock
    ModelFactory.populate_mock(self, **kwargs)
  File "/Users/aphearin/anaconda/lib/python2.7/site-packages/halotools-0.0a0-py2.7-macosx-10.5-x86_64.egg/halotools/empirical_models/factories/model_factory_template.py", line 143, in populate_mock
    test_consistency_with_existing_mock(**kwargs)
  File "/Users/aphearin/anaconda/lib/python2.7/site-packages/halotools-0.0a0-py2.7-macosx-10.5-x86_64.egg/halotools/empirical_models/factories/model_factory_template.py", line 122, in test_consistency_with_existing_mock
    raise HalotoolsError(inconsistent_redshift_error_msg % (redshift, self.mock.halocat.redshift))
HalotoolsError: Inconsistency between the model redshift = -0.00 and the halocat redshift = 1.99.
You should instantiate a new model object if you wish to switch halo catalogs.

**Comment by aphearin** [comment]
Resolved by #306
