### ISSUE TITLE
bug in download script

### ISSUE THREAD

**Issue by aphearin** [astropy/halotools#562]
When attempting to download higher-redshift catalogs of Bolshoi, there are two problems:

1. The script fails with an error message that would confuse any new user because there are no particles available for the high-z bolshoi snapshots. 

2. The above issue is resolved by throwing the -halos_only flag, but then the script raises the following even less informative exception at the end:

Total runtime to download pre-processed halo catalog = 126.8 seconds

Traceback (most recent call last):
  File "scripts/download_additional_halocat.py", line 177, in <module>
    + new_ptcl_log_entry.fname + "\n\n"
NameError: name 'new_ptcl_log_entry' is not defined

**Comment by aphearin** [comment]
The second bug also appears when throwing the -halos_only flag for bolplanck z=0.5, so it's possible that the second bug occurs for *any* usage of this flag. 

Similarly, when throwing the -ptcls_only flag after initially downloading bolplack z=0.5 halos, I get the following error:

Traceback (most recent call last):
  File "scripts/download_additional_halocat.py", line 177, in <module>
    + new_ptcl_log_entry.fname + "\n\n"
NameError: name 'new_halo_log_entry' is not defined

The download proceeds without problems in either case, it's just that this exception should not be raised at the end. 

No such bugs appear when omitting either "only" flag.
