### ISSUE TITLE
AppVeyor fails unexpectedly

### ISSUE THREAD

**Issue by aphearin** [astropy/halotools#773]
Thanks to @bsipocz and @MSeifert04 for helping pin down a new and somewhat mysteriously arising AppVeyor build failure. This was revealed, but unrelated to, #771. Traceback included below 

```
Traceback (most recent call last):
  File "setup.py", line 69, in <module>
    cmdclassd = register_commands(PACKAGENAME, VERSION, RELEASE)
  File "c:\projects\halotools\astropy_helpers\astropy_helpers\setup_helpers.py", line 142, in register_commands
    from .commands.build_sphinx import (AstropyBuildSphinx,
  File "c:\projects\halotools\astropy_helpers\astropy_helpers\commands\build_sphinx.py", line 17, in <module>
    from sphinx.setup_command import BuildDoc as SphinxBuildDoc
  File "C:\conda\envs\test\lib\site-packages\Sphinx-1.6.2-py2.7.egg\sphinx\setup_command.py", line 23, in <module>
    from sphinx.application import Sphinx
  File "C:\conda\envs\test\lib\site-packages\Sphinx-1.6.2-py2.7.egg\sphinx\application.py", line 33, in <module>
    from sphinx.environment import BuildEnvironment
  File "C:\conda\envs\test\lib\site-packages\Sphinx-1.6.2-py2.7.egg\sphinx\environment\__init__.py", line 45, in <module>
    from sphinx.util.websupport import is_commentable
  File "C:\conda\envs\test\lib\site-packages\Sphinx-1.6.2-py2.7.egg\sphinx\util\websupport.py", line 11, in <module>
    from sphinxcontrib.websupport.utils import is_commentable  # NOQA
  File "C:\conda\envs\test\lib\site-packages\sphinxcontrib\websupport\__init__.py", line 15, in <module>
    from sphinxcontrib.websupport.core import WebSupport  # NOQA
  File "C:\conda\envs\test\lib\site-packages\sphinxcontrib\websupport\core.py", line 17, in <module>
    from jinja2 import Environment, FileSystemLoader
  File "C:\conda\envs\test\lib\site-packages\jinja2\__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "C:\conda\envs\test\lib\site-packages\jinja2\environment.py", line 15, in <module>
    from jinja2 import nodes
  File "C:\conda\envs\test\lib\site-packages\jinja2\nodes.py", line 19, in <module>
    from jinja2.utils import Markup
  File "C:\conda\envs\test\lib\site-packages\jinja2\utils.py", line 486, in <module>
    MutableMapping.register(LRUCache)
  File "C:\conda\envs\test\lib\abc.py", line 109, in register
    if issubclass(subclass, cls):
  File "C:\conda\envs\test\lib\abc.py", line 180, in __subclasscheck__
    if issubclass(subclass, scls):
  File "C:\conda\envs\test\lib\site-packages\typing.py", line 1229, in __subclasscheck__
    return super(GenericMeta, self).__subclasscheck__(cls)
TypeError: super() argument 1 must be type, not None
Command exited with code 1
```

**Comment by bsipocz** [comment]
@aphearin - Why do you need sphinx for the appveyor testing? While in theory the tests and everything should work when it's present, but we see issues (with very similar traceback to this) with with the dependencies that sphinx 1.6+ brings on board.

So for now I would suggest to stick with <1.6 sphinx when users are running to this issue, otherwise #774 should take care of the fail.

**Comment by aphearin** [comment]
Good point - I definitely do not need sphinx for appveyor testing. This is needless, but has just never come up before 1.6 so I had not noticed it.
